const {chromium} = require('playwright');
const fs = require('fs');
const assert = require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.LUNA_CHROMIUM_PATH,args:JSON.parse(process.env.LUNA_CHROMIUM_ARGS||'[]')});
 const page=await browser.newPage({viewport:{width:1280,height:720}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{window.mediaCalls=[];window.webapis={avplay:{state:'IDLE',open(){window.mediaCalls.push('open');},setDisplayRect(){},setListener(){},prepareAsync(fn){setTimeout(fn,50);},play(){this.state='PLAYING';window.mediaCalls.push('play');},pause(){this.state='PAUSED';},stop(){this.state='IDLE';window.mediaCalls.push('stop');},close(){window.mediaCalls.push('close');},getState(){return this.state;},getDuration(){return 60000;},getCurrentTime(){return 1000;},seekTo(){}}};});
 await page.route('**/*',async route=>{
   const url=route.request().url();
   const reply=body=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)});
   if(url==='http://luna.test/')return route.fulfill({contentType:'text/html',body:fs.readFileSync('tv/index.html','utf8')});
   if(url.includes('$WEBAPIS'))return route.fulfill({contentType:'application/javascript',body:''});
   if(url.includes('/auth/v1/token'))return reply({access_token:'mock',refresh_token:'mock-refresh',expires_in:3600});
   if(url.includes('/account'))return reply({id:'owner-1',email:'teste@example.invalid',plano:'Grátis',status:'inativo',premium:false});
   if(url.includes('/catalog'))return reply({items:[{id:'1',nome:'Filme teste',categoria:'Filmes',premium:false},{id:'2',nome:'Episódio teste',categoria:'Séries',serie_nome:'Luna',temporada:1,episodio:1,premium:false}],next:null});
   if(url.includes('/games'))return reply({items:[{id:'g1',title:'Meu quiz',kind:'quiz',content:{questions:[{prompt:'Quanto é 2 + 2?',options:['3','4','5'],answer:1}]}},{id:'g2',title:'Minha memória',kind:'memory',content:{items:['Lua','Sol']}}]});
   if(url.includes('/play?id=1'))return reply({url:'https://media.test/v.mp4',nome:'Filme teste'});
   return route.abort();
 });
 await page.goto('http://luna.test/');
 assert.equal(await page.locator('.menu button').count(),19);
 await page.getByRole('button',{name:'Histórias da Luna',exact:true}).click();
 await page.getByRole('button',{name:'Luna e o Livro Mágico',exact:true}).click();
 await page.getByRole('button',{name:'Próximo capítulo',exact:true}).click();
 assert.match(await page.locator('.story').innerText(),/floresta/);
 await page.getByRole('button',{name:'Menu da TV',exact:true}).click();
 await page.getByRole('button',{name:'Minha conta',exact:true}).click();
 await page.locator('#email').fill('teste@example.invalid');await page.locator('#password').fill('test-only');
 await page.getByRole('button',{name:'Entrar',exact:true}).click();
 await page.getByText('Conta conectada.',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Menu da TV',exact:true}).click();
 await page.getByRole('button',{name:'Filmes',exact:true}).click();
 await page.getByRole('button',{name:/Filme teste/}).click();
 await page.getByRole('button',{name:'▶ Assistir',exact:true}).click();
 await page.getByText('Filme teste · Reproduzindo',{exact:true}).waitFor();
 await page.keyboard.press('Escape');assert.equal(await page.locator('#player').isVisible(),false);
 assert.ok((await page.evaluate(()=>window.mediaCalls)).includes('close'));
 await page.getByRole('button',{name:'Menu da TV',exact:true}).click();
 await page.getByRole('button',{name:'Séries',exact:true}).click();
 await page.getByRole('button',{name:'Luna',exact:true}).click();
 await page.getByRole('button',{name:'Temporada 1',exact:true}).click();
 await page.getByRole('button',{name:/Episódio teste/}).waitFor();
 await page.getByRole('button',{name:'Menu da TV',exact:true}).click();
 await page.getByRole('button',{name:'Faça seu próprio jogo',exact:true}).click();
 await page.getByRole('button',{name:'Meu quiz',exact:true}).click();
 await page.getByRole('button',{name:'4',exact:true}).click();
 await page.getByRole('button',{name:'Próxima fase',exact:true}).click();
 assert.match(await page.locator('#content').innerText(),/Você concluiu o jogo/);
 await page.getByRole('button',{name:'Menu da TV',exact:true}).click();
 await page.getByRole('button',{name:'Atividades escolares',exact:true}).click();
 await page.getByRole('button',{name:'4–5 anos',exact:true}).click();
 await page.getByRole('button',{name:'Animais',exact:true}).click();
 await page.getByRole('button',{name:'Coelho',exact:true}).click();
 assert.match(await page.locator('#message').innerText(),/acertou/);
 await page.getByRole('button',{name:'Menu da TV',exact:true}).click();
 await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowDown');
 assert.equal(await page.locator('button:focus').count(),1);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:'/tmp/luna-tv-home.png'});
 assert.deepEqual(errors,[]);
 console.log('PASS: 19 menus, stories, mock login/catalog, AVPlay lifecycle, series, custom quiz, activities and remote focus.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
